/*DROP TABLE ITEM;
DROP TABLE ITEMGROUP;*/

CREATE DATABASE groupdb ENCODING 'UTF-8';

CREATE TABLE ITEMGROUP (
  ID SERIAL PRIMARY KEY,
  TITLE VARCHAR(100)  UNIQUE NOT NULL);

CREATE TABLE ITEM (
  ID SERIAL PRIMARY KEY,
  TITLE VARCHAR(100) UNIQUE NOT NULL,
  GROUPID INTEGER,
  FOREIGN KEY (GROUPID) REFERENCES ITEMGROUP(ID) );

INSERT INTO ITEMGROUP(TITLE) VALUES('Овощи');
INSERT INTO ITEMGROUP(TITLE) VALUES('Фрукты');
INSERT INTO ITEMGROUP(TITLE) VALUES('Ягоды');

INSERT INTO ITEM(TITLE,GROUPID) VALUES('Тыква',1);
INSERT INTO ITEM(TITLE,GROUPID) VALUES('Морковь',1);
INSERT INTO ITEM(TITLE,GROUPID) VALUES('Бананы',2);
INSERT INTO ITEM(TITLE,GROUPID) VALUES('Манго',2);
INSERT INTO ITEM(TITLE,GROUPID) VALUES('Черника',3);
INSERT INTO ITEM(TITLE,GROUPID) VALUES('Брусника',3);